fastq_dir: "/mnt/evafs/groups/sfglab/jborkowska/OPUS_replication_stress/IBLESS/fastq"
outdir: "results/iblesse_eden_test"

sample_pattern: "*_R1.fastq.gz"

genome_fasta: "/mnt/evafs/groups/sfglab/jborkowska/hg38/hg38_reference/hg38_reference.fna"
genome_index: "/mnt/evafs/groups/sfglab/jborkowska/hg38/hg38_reference/hg38_reference.fna"

break_calling:
  mode: "per_base"
  bin_size: 1000
  remove_sgrdi: true  
