fastq_dir: "/mnt/evafs/groups/sfglab/jborkowska/OPUS_replication_stress/IBLESS/fastq"
outdir: "/mnt/evafs/groups/sfglab/pranjul/I-SAGE_output"
logdir: "/mnt/evafs/groups/sfglab/pranjul/I-SAGE_log"

sample_pattern: "*_R1.fastq.gz"

genome_fasta: "/mnt/evafs/groups/sfglab/jborkowska/hg38/hg38_reference/hg38_reference.fna"
genome_index: "/mnt/evafs/groups/sfglab/jborkowska/hg38/hg38_reference/hg38_reference.fna"

break_calling:
  mode: "per_base"
  bin_size: 1000
  remove_sgrdi: true

viz:
  enabled: true
  bin_sizes: [250, 500, 1000]

normalization:
  method: dsb_cpm
  scale: 1000000

stats:
  enabled: true
  ebv_regex: "(?i)^chrEBV$"
  fdr: 0.05
  replicate_method: meta_fisher   # or pooled

  conditions:
    APH:  ["GM12878_iBLESS_rep1_APH", "GM12878_iBLESS_rep3_APH"]
    DMSO: ["GM12878_iBLESS_rep1_DMSO", "GM12878_iBLESS_rep3_DMSO"]
    HU:   ["GM12878_iBLESS_rep3_HU"]
    H2O:  ["GM12878_iBLESS_rep3_H2O"]

  contrasts:
    - name: "APH_vs_DMSO"
      case_condition: "APH"
      control_condition: "DMSO"

    - name: "HU_vs_H2O_rep3"
      case_condition: "HU"
      control_condition: "H2O"

validation:
  enabled: true
  fdr: 0.05
  downsample_fracs: "1.0,0.5,0.25,0.1"
  downsample_reps: 1
  spikein_bins: 1000
  spikein_mult: 3.0
  seed: 123